export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST';
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_CANCEL = 'COUNTRIES_REQUEST_CANCEL';
export const COUNTRIES_REQUEST_CANCELED = 'COUNTRIES_REQUEST_CANCELED';